### ISSUE TITLE
[Subgraph] Transactions not indexed

### ISSUE THREAD

**Issue by portuu3** [humanprotocol/human-protocol#2521]
**Describe the bug**
Transactions with method different to `Transfer` are not being indexed

**To Reproduce**
Go to subgraph and query for transactions for address 0x3deedd7166bda81d87ddda4c7a761d6664c8ac16 and compare with https://polygonscan.com/token/0xc748B2A084F8eFc47E086ccdDD9b7e67aEb571BF?a=0x3deedd7166bda81d87ddda4c7a761d6664c8ac16

**Expected behavior**
All transactions in scanner should be indexed

**Comment by flopez7** [comment]
The issue occurs because the address `0x3deedd7166bda81d87ddda4c7a761d6664c8ac16` is a Gnosis smart contract that acts as an intermediary for transactions, meaning it's not the actual sender. The real user behind the transactions is `0x0CEe8EdcC728DB54794ddfc2a421f6cdEFF8FC17`, whose transactions are indexed correctly in our system. This explains why the transactions seen on PolygonScan aren't directly reflected in the subgraph for the Gnosis contract, as only the real sender is being indexed.
