### ISSUE TITLE
Job Launcher - Routing protocol - get fees cost estimation

### ISSUE THREAD

**Issue by portuu3** [humanprotocol/human-protocol#595]
**Description**
Job launcher should show the fees for creating an escrow on each network. 
Then the user can choose the network or let the routing protocol choose based on this and other indicators.

**Motivation**
Users should be able to know why the routing protocol chooses a network or another and also let them make the decision.

**Implementation details** 
Create an endpoint to server the cost values.
Calculation: [current avg gas price] * [gas cost of launching the escrow]

**Comment by s7c** [comment]
ACCEPTANCE CRITERIA:

1.  The integrated  endpoint provide  real-time fee updates.
2.  Ensure that the system dynamically fetches and updates the current average gas price in real-time for accurate fee calculations in order to for the users to see up-to-date information when making decisions.
3. Update relevant documentation to include the new details
